services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=aston
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
